name: Code Linter

on:
  pull_request:
    branches:
      - main

jobs:
  Formate:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Swiftformat
        run: brew install swift-format

      - name: Format code
        run: swift-format --lint .
