name: Code Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  format_code:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install swift-format
        run: brew install swiftformat

      - name: Format code
        run: swiftformat --config ./swift-format-config.yml --lint .
